name: Publish Ruby Gem

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      version:
        description: "0.3.1"
        required: true

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Setup gems
      run: |
        bash .github/setup-rubygems.sh
      
    - name: Publish to RubyGems
      run: |
        gem build ruby-kubernetes-controller.gemspec
        gem push ruby-kubernetes-controller-$VERSION_TAG.gem 
      env:
        VERSION_TAG: "${{github.event.inputs.version}}"
